user/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, session
import sqlite3

user_bp = Blueprint('user', __name__, template_folder='templates')

# SQLite Database Setup
conn = sqlite3.connect('database.db')
c = conn.cursor()
c.execute('''CREATE TABLE IF NOT EXISTS users
             (id INTEGER PRIMARY KEY AUTOINCREMENT,
              first_name TEXT,
              last_name TEXT,
              email TEXT,
              password TEXT)''')

# Create the orders table if it doesn't exist
c.execute('''CREATE TABLE IF NOT EXISTS orders
             (id INTEGER PRIMARY KEY AUTOINCREMENT,
              product_id INTEGER,
              product_name TEXT,
              price REAL,
              quantity INTEGER,
              FOREIGN KEY (product_id) REFERENCES products(id))''')

conn.commit()
conn.close()


@user_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        # Check if user exists in the database
        conn = sqlite3.connect('database.db')
        c = conn.cursor()
        c.execute("SELECT * FROM users WHERE email = ? AND password = ?", (email, password))
        user = c.fetchone()
        conn.close()

        if user:
            session['first_name'] = user[1]
            return render_template('user_dashboard.html', template='base.html', email=email)
        else:
            return "No such user exists."

    return render_template('user_login.html')


@user_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        first_name = request.form['first_name']
        last_name = request.form['last_name']
        email = request.form['email']
        password = request.form['password']

        # Store user details in SQLite database
        conn = sqlite3.connect('database.db')
        c = conn.cursor()
        c.execute("INSERT INTO users (first_name, last_name, email, password) VALUES (?, ?, ?, ?)",
                  (first_name, last_name, email, password))
        conn.commit()
        conn.close()

        return redirect('/user/login')

    return render_template('user_signup.html')

@user_bp.route('/sections')
def section_list():
    # Retrieve the list of sections from the database
    conn = sqlite3.connect('database.db')
    c = conn.cursor()
    c.execute("SELECT * FROM sections")
    sections = c.fetchall()
    conn.close()

    return render_template('section_list_user.html', sections=sections)


@user_bp.route('/product_list')
def user_product_list():
    # Retrieve the product list from the database
    conn = sqlite3.connect('database.db')
    c = conn.cursor()
    c.execute("SELECT * FROM products")
    products = c.fetchall()
    conn.close()
    return render_template('product_list_user.html', products=products)


@user_bp.route('/products_by_section/<int:section_id>')
def products_by_section(section_id):
    # Retrieve the section name from the database
    conn = sqlite3.connect('database.db')
    c = conn.cursor()
    c.execute("SELECT section_name FROM sections WHERE id = ?", (section_id,))
    section_name = c.fetchone()[0]
    
    # Retrieve the products for the specified section ID from the database
    c.execute("SELECT * FROM products WHERE section_id = ?", (section_id,))
    products = c.fetchall()
    conn.close()

    return render_template('products_by_section_user.html', products=products, section_name=section_name,section_id=section_id)



@user_bp.route('/add_to_cart/<int:product_id>', methods=['POST'])
def add_to_cart(product_id):
    # Retrieve the product details from the database based on the product ID
    conn = sqlite3.connect('database.db')
    c = conn.cursor()
    c.execute("SELECT * FROM products WHERE id = ?", (product_id,))
    product = c.fetchone()

    if product is not None and product[6] is not None and product[6] > 0:  # Assuming the quantity column is at index 7
        # Check if the product is already in the user's orders
        c.execute("SELECT * FROM orders WHERE product_id = ?", (product_id,))
        existing_order = c.fetchone()

        if existing_order is not None:
            # If the product is already in the user's orders, increment the quantity
            new_quantity = existing_order[4] + 1  # Assuming the quantity column is at index 4
            c.execute("UPDATE orders SET quantity = ? WHERE product_id = ?", (new_quantity, product_id))
            conn.commit()
        else:
            # Insert the purchased product details into the "orders" table
            c.execute("INSERT INTO orders (product_id, product_name, price, quantity) VALUES (?, ?, ?, ?)",
                      (product[0], product[1], product[4], 1))  # Assuming the respective columns for product_id, product_name, price, and quantity
            conn.commit()

        # Calculate the new quantity after adding to cart
        new_quantity = product[6] - 1  # Subtracting 1 from the current quantity
        print(new_quantity)
        if new_quantity >= 0:
            # Update the product quantity in the database
            c.execute("UPDATE products SET quantity = ? WHERE id = ?", (new_quantity, product_id))
            conn.commit()

            conn.close()

            # Perform any other necessary actions related to adding to cart, such as updating the product status

            # Redirect the user to a success message or relevant route
            return "Product added to cart successfully"
        else:
            # If the product quantity is insufficient, return an error message
            conn.close()
            return "Insufficient quantity. Product cannot be added to cart."
    else:
        # If the product is not found or the quantity is zero or None, return an error message
        conn.close()
        return "Error: Product not available."



@user_bp.route('/product_list', methods=['GET', 'POST'])
def search_product_list():
    if request.method == 'POST':
        # Retrieve the search query from the form
        search_query = request.form.get('search_query')

        # Retrieve the filtered product list from the database based on the search query
        conn = sqlite3.connect('database.db')
        c = conn.cursor()
        c.execute("SELECT * FROM products WHERE productname LIKE ? OR rate LIKE ? OR manufacture_date LIKE ? OR fexpiry_date LIKE ? OR id LIKE ?", ('%' + search_query + '%', '%' + search_query + '%', '%' + search_query + '%', '%' + search_query + '%', '%' + search_query + '%'))
        products = c.fetchall()
        conn.close()
        print("search")
        print(products)
        if products == []:
            return redirect('/user/product_list')
        return render_template('product_list_user.html', products=products)


@user_bp.route('/products_by_section/<int:section_id>', methods=['GET', 'POST'])
def search_product_list_by_section(section_id):
    if request.method == 'POST':
        # Retrieve the search query from the form
        search_query = request.form.get('search_query')
        # Retrieve the filtered product list from the database based on the search query
        conn = sqlite3.connect('database.db')
        c = conn.cursor()
        c.execute("SELECT * FROM products WHERE (productname LIKE ? OR rate LIKE ? OR manufacture_date LIKE ? OR fexpiry_date LIKE ? OR id LIKE ?) AND section_id = ?", ('%' + search_query + '%', '%' + search_query + '%', '%' + search_query + '%', '%' + search_query + '%', '%' + search_query + '%', section_id))
        products = c.fetchall()
        conn.close()
        print("user search")
        print(section_id)
        print(products)
        if not products:  # Check if products list is empty
            # Redirect to the products_by_section URL
            print("Enter")
            return redirect(url_for('user.products_by_section', section_id=section_id))
        return render_template('product_list_user_section.html', products=products)
    return render_template('product_list_user_section.html', products=[])  # Empty list for initial rendering



@user_bp.route('/orders')
def user_orders():
    # Retrieve the purchased products from the database
    conn = sqlite3.connect('database.db')
    c = conn.cursor()
    c.execute("SELECT * FROM orders")
    orders = c.fetchall()
    conn.close()
    
    # It will show the total amount of money which need to pay to the user
    total_amount = 0  # Variable to store the total amount

    # Calculate the total amount
    for order in orders:
        price = order[3]  # Assuming the price column is at index 3
        quantity = order[4]  # Assuming the quantity column is at index 4
        total_amount += price * quantity
        
    return render_template('user_orders.html',  orders=orders, total_amount=total_amount)


@user_bp.route('/logout')
def logout():
    # Log out the user
    session.pop('first_name', None)
    # Redirect the user to the login page or any other page
    return redirect('/user/login')

@user_bp.route('/user_dashboard')
def user_dashboard():
    return render_template('user_dashboard.html', template='base.html')





templates/add_products.html
{% extends 'base_admin.html' %}

{% block content %}
    <h1>Add Product</h1>
    <form method="POST" action="/admin/add_product">
        <label for="id">ID:</label>
        <input type="text" id="id" name="id" required><br>

        <label for="productname">Name:</label>
        <input type="text" id="productname" name="productname" required><br>

        <label for="manufacture_date">Manufacture Date:</label>
        <input type="date" id="manufacture_date" name="manufacture_date" required><br>

        <label for="fexpiry_date">Expiry Date:</label>
        <input type="date" id="fexpiry_date" name="fexpiry_date" required><br>

        <label for="rate">Rate per unit:</label>
        <input type="number" id="rate" name="rate" step="0.01" required><br>

        <label for="unit">Unit:</label>
        <select id="unit" name="unit" required>
            <option value="Kg">Kg</option>
            <option value="Litre">Litre</option>
        </select><br>
        <label for="quantity">Quantity</label>
        <input type="number" id="quantity" name="quantity" required><br>
        <label for="section_id">Section Id:</label>
        <input type="number" id="section_id" name="section_id" required><br>
        <input type="submit" value="Add Product">
    </form>
{% endblock %}

templates/admin_dashboard.html
{% extends 'base_admin.html' %}

{% block content %}
    <h1>Welcome to the Admin Dashboard</h1>

    <div class="admin-dashboard">
        <a href="{{ url_for('admin.add_product') }}">Add Product</a>
        <a href="{{ url_for('admin.create_section') }}">Add Section</a>
        <a href="{{ url_for('admin.section_list') }}">View Section</a>
        <a href="{{ url_for('admin.product_list') }}">View Product List</a>
    </div>
{% endblock %}

templates/admin_login.html
<!DOCTYPE html>
<html>
<head>
    <title>Admin Login</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='admin_login.css') }}">
</head>
<body>
    <h1>Admin Login</h1>
    <form method="post" action="/admin/login">
        <input type="email" name="email" placeholder="Email" required><br>
        <input type="password" name="password" placeholder="Password" required><br>
        <input type="tel" name="phone_number" placeholder="Phone Number" required><br>
        <input type="submit" value="Login">
    </form>
    <a href="/admin/signup">Signup</a>
</body>
</html>

templates/admin_signup.html
<!DOCTYPE html>
<html>
<head>
    <title>Admin Signup</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='admin_signup.css') }}">

</head>
<body>
    <h1>Admin Signup</h1>
    <form method="post" action="/admin/signup">
        <input type="text" name="first_name" placeholder="First Name" required><br>
        <input type="text" name="last_name" placeholder="Last Name" required><br>
        <input type="email" name="email" placeholder="Email" required><br>
        <input type="text" name="phone_number" placeholder="Phone Number" required><br>
        <input type="password" name="password" placeholder="Password" required><br>
        <input type="submit" value="Signup">
    </form>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>User</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user_dashboard.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='section_list_user.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='product_list_user.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='products_by_section_user.css') }}">
    <style>
        /* Add your additional CSS styles here */

        .logged-in-user {
            font-weight: bold;
        }

        .button-container {
            margin-top: 10px;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        .home-button {
            margin-right: 10px;
        }
    </style>
</head>
<body>
    <h1>Grocery Store</h1>
    <div class="user-info">
        {% if session['first_name'] %}
            <div class="logged-in-user">Logged in as: {{ session['first_name'] }}</div>
            <div class="button-container">
                <!-- Add home button -->
                <a class="home-button" href="/user/user_dashboard">&#127968;</a>
                {% block logout_button %}
                    <a class="logout-button" href="/user/logout">Log Out</a>
                {% endblock %}
            </div>
        {% endif %}
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/edit_product.html
{% extends 'base_admin.html' %}

{% block content %}
    <h1>Edit Product</h1>

    <form method="POST" action="/admin/edit_product/{{ product[0] }}">
        <label for="productname">Product Name:</label>
        <input type="text" name="productname" value="{{ product[1] }}" required><br>

        <label for="manufacture_date">Manufacture Date:</label>
        <input type="date" name="manufacture_date" value="{{ product[2] }}" required><br>

        <label for="expiry_date">Expiry Date:</label>
        <input type="date" name="fexpiry_date" value="{{ product[3]}}" required><br>

        <label for="rate_per_unit">Rate per unit:</label>
        <input type="text" name="rate_per_unit" value="{{ product[4] }}" required><br>

        <label for="unit">Unit:</label>
        <select id="unit" name="unit" value="{{ product[5] }}" required>
            <option value="Kg">Kg</option>
            <option value="Litre">Litre</option></select><br>

        <label for="quantity">Quantity:</label>
        <input type="text" name="quantity" value="{{ product[6] }}" required><br>

        <label for="section_id">Section ID:</label>
        <input type="text" name="section_id" value="{{ product[7] }}" required><br>


        <button type="submit">Update</button>
    </form>
{% endblock %}

templates/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Home Page</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
</head>
<body>
    <div class="container">
        <h1>Welcome to the Home Page</h1>
        <a href="/user/login" class="user-btn"><span>User</span></a>
        <a href="/admin/login" class="admin-btn"><span>Admin</span></a>
    </div>
</body>
</html>

templates/product_list_admin.html
<!DOCTYPE html>
<html>
<head>
    <title>Admin Product List</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='product_list_admin.css') }}">
</head>
<body>
    <h1>Admin Product List</h1>

    <form method="post" action="{{ url_for('admin.search_product_list') }}">
        <input type="text" name="search_query" placeholder="Search bar">
        <button type="submit">Search</button>
    </form>

    <table>
        <tr>
            <th>Product ID</th>
            <th>Product Name</th>
            <th>Manufacture Date</th>
            <th>Expiry Date</th>
            <th>Rate per unit</th>
            <th>Unit</th>
            <th>Quantity</th>
            <th>Section ID</th>
            <th>Action</th>
        </tr>
        {% for product in products %}
        <tr>
            <td>{{ product[0] }}</td>
            <td>{{ product[1] }}</td>
            <td>{{ product[2] }}</td>
            <td>{{ product[3] }}</td>
            <td>{{ product[4] }}</td>
            <td>{{ product[5] }}</td>
            <td>{{ product[6] }}</td>
            <td>{{ product[7] }}</td>
            <td>
                <div class="button-group">
                    <a href="{{ url_for('admin.edit_product', product_id=product[0]) }}" class="btn-edit">
                                   <img src="{{ url_for('static', filename='edit.png') }}" alt="Edit" class="icon">
                    </a>
                    <form method="POST" action="/admin/product_list" class="delete-form">
                      <input type="hidden" name="id" value="{{ product[0] }}">
                      <input type="hidden" name="action" value="delete_product">
                      <button type="" class="btn-delete">
                        <img src="{{ url_for('static', filename='delete.png') }}" alt="Delete" class="icon">
                      </button>
                    </form>
                </div>
            </td>
        </tr>
        {% endfor %}
    </table>    
    <a class="add-button" href="{{ url_for('admin.add_product') }}">Add Product</a>

</body>
</html>

templates/product_list_admin_section.html
{% extends 'base_admin.html' %}
{% block content %}
    <h1>Admin Product List</h1>
    <table>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Manufacture Date</th>
            <th>Expiry Date</th>
            <th>Rate per unit</th>
            <th>Unit</th>
            <th>Section ID</th>
        </tr>
        {% for product in products %}
        <tr>
            <td>{{ product[0] }}</td>
            <td>{{ product[1] }}</td>
            <td>{{ product[2] }}</td>
            <td>{{ product[3] }}</td>
            <td>{{ product[4] }}</td>
            <td>{{ product[5] }}</td>
            <td>{{ product[6] }}</td>
        </tr>
        {% endfor %}
    </table>
    {% endblock %}

templates/product_list_user_section.html
{% extends 'base.html' %}
{% block content %}

    <h1>User Product List</h1>
    <table>
        <tr>
            <th>Product ID</th>
            <th>Name</th>
            <th>Manufacture Date</th>
            <th>Expiry Date</th>
            <th>Rate per unit</th>
            <th>Unit</th>
            <th>Section ID</th>
            <th>Action</th>
        </tr>
        {% for product in products %}
        <tr>
            <td>{{ product[0] }}</td>
            <td>{{ product[1] }}</td>
            <td>{{ product[2] }}</td>
            <td>{{ product[3] }}</td>
            <td>{{ product[4] }}</td>
            <td>{{ product[5] }}</td>
            <td>{{ product[6] }}</td>
            <td><a href="{{ url_for('user.add_to_cart', product_id=product[0]) }}">Buy</a></td>
        </tr>
        {% endfor %}
    </table>
    <br>
    <a href="{{ url_for('user.user_orders') }}">Your Orders</a>
    <br>
    <br>
{% endblock %}

templates/products_by_section_user.html
{% extends 'base.html' %}

{% block content %}

    <h1>User Products by Section CE</h1>
    <h2>{{ section_name }}</h2>
    
    <form method="post" action="{{ url_for('user.search_product_list_by_section', section_id=section_id) }}">
        <input type="text" name="search_query" placeholder="Search bar">
        <button type="submit">Search</button>
    </form>
    

    <table>
        <tr>
            <th>Product ID</th>
            <th>Name</th>
            <th>Manufacture Date</th>
            <th>Expiry Date</th>
            <th>Rate per Unit</th>
            <th>Unit</th>
            <th>Action</th>
        </tr>
        {% for product in products %}
        <tr>
            <td>{{ product[0] }}</td>
            <td>{{ product[1] }}</td>
            <td>{{ product[2] }}</td>
            <td>{{ product[3] }}</td>
            <td>{{ product[4] }}</td>
            <td>{{ product[5] }}</td>
            <td>
                {% if product[6] is not none and product[6] > 0 %}
                <form method="post" action="{{ url_for('user.add_to_cart', product_id=product[0]) }}">
                    <button type="submit">Add to Cart</button>
                </form>
                {% else %}
                    <span>Out of Stock</span>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
    <br>
    <a href="{{ url_for('user.user_orders') }}">Your Orders</a>
{% endblock %}

templates/user_dashboard.html
{% extends 'base.html' %}

{% block content %}
    <h1>User Dashboard</h1>

    <div class="user-dashboard">
        <a href="{{ url_for('user.section_list') }}">View Section</a>
        <a href="{{ url_for('user.user_product_list') }}">View Product List</a>
        <a href="{{ url_for('user.user_orders') }}">Your Orders</a>
    </div>
{% endblock %}

templates/user_login.html
<!DOCTYPE html>
<html>
<head>
    <title>User Login</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user_login.css') }}">
</head>
<body>
    <h1>User Login</h1>
    <form method="post" action="/user/login">
        <input type="email" name="email" placeholder="Email" required><br>
        <input type="password" name="password" placeholder="Password" required><br>
        <input type="submit" value="Login">
    </form>
    <a href="/user/signup">Signup</a>
</body>
</html>

templates/user_signup.html
<!DOCTYPE html>
<html>
<head>
    <title>User Signup</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user_signup.css') }}">
</head>
<body>
    <h1>User Signup</h1>
    <form method="post" action="/user/signup">
        <input type="text" name="first_name" placeholder="First Name" required><br>
        <input type="text" name="last_name" placeholder="Last Name" required><br>
        <input type="email" name="email" placeholder="Email" required><br>
        <input type="password" name="password" placeholder="Password" required><br>
        <input type="submit" value="Signup">
    </form>
</body>
</html>